version: '3'
services:
  first_app:
    container_name: simple-app
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/movie_db
      SPRING_DATASOURCE_USERNAME: movie_rental
      SPRING_DATASOURCE_PASSWORD: movie_pw
    links:
      - postgres
      - redis-server
  postgres:
    container_name: movie_rental_system
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_rental
      POSTGRES_PASSWORD: movie_pw

  redis-server:
    hostname: redis
    container_name: movie_rental_system-redis_db
    image: 'redis'
    ports:
      - "6379:6379"